# Generated by Django 5.0.7 on 2025-05-08 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testimonial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='para1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='para2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_1_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_2_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_3_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_4_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
