# Generated by Django 5.0.7 on 2025-05-08 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_about_para1_alter_about_para2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
